# Generated by Django 3.1.6 on 2021-02-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_added_sent_remainder_flag_to_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sent_remainder',
            new_name='sent_reminder',
        ),
    ]
