# Generated by Django 3.1.6 on 2021-02-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210214_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remind_at',
            field=models.DateTimeField(null=True),
        ),
    ]
